Commented for testing

diff --git a/.github/workflows/terraform-enviromements-action.yml b/.github/workflows/terraform-enviromements-action.yml
--- a/.github/workflows/terraform-enviromements-action.yml
+++ b/.github/workflows/terraform-enviromements-action.yml
@@ -50,39 +50,39 @@ jobs:
           lsb_release -a
           hostnamectl
           sh scripts/backend-tf.sh
-      - name: Terraform fmt
-        id: fmt
-        run: terraform -fmt -check
-        continue-on-error: true
+#       - name: Terraform fmt
+#         id: fmt
+#         run: terraform -fmt -check
+#         continue-on-error: true
 
-      - name: Terraform Init
-        id: init
-        env: 
-          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
-          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCEKT_KEY_NAME }}
-        run: |
-          pwd
-          ls
-          cd terraform/environments/dev/
-          pwd
-          terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key={AWS_BUCKET_KEY_NAME}"
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+#       - name: Terraform Init
+#         id: init
+#         env: 
+#           AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
+#           AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCEKT_KEY_NAME }}
+#         run: |
+#           pwd
+#           ls
+#           cd terraform/environments/dev/
+#           pwd
+#           terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key={AWS_BUCKET_KEY_NAME}"
+#       - name: Terraform Validate
+#         id: validate
+#         run: terraform validate -no-color
       
-      - name: Terrafrom plan
-        id: plan
-        run: |
-          pwd
-          ls
-          cd terraform/environments/dev/
-          terraform plan -no-color
+#       - name: Terrafrom plan
+#         id: plan
+#         run: |
+#           pwd
+#           ls
+#           cd terraform/environments/dev/
+#           terraform plan -no-color
 
-        continue-on-error: true
-      - name: Terraform Plan Status
-        if: steps.plan.outcome =='failure'
-        run: exit 1
+#         continue-on-error: true
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome =='failure'
+#         run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false 
+#       - name: Terraform Apply
+#         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#         run: terraform apply -auto-approve -input=false 
